import { SiteSettings } from "@/lib/site-settings"
import { getSiteUrl } from "@/lib/site-url"
import { PASSWORD_RESET_PATH } from "@/lib/password-reset-routes"

export type MailDnsRecord = {
  type: "TXT" | "CNAME"
  host: string
  value: string
  purpose: string
}

export type MailDeliverabilityReport = {
  canonicalDomain: string
  canonicalResetUrl: string
  fromName: string
  fromEmail: string
  replyTo: string
  smtpHost: string
  smtpUser: string
  providerLabel: string
  warnings: string[]
  recommendations: string[]
  dnsRecords: MailDnsRecord[]
}

function envFirst(...values: Array<string | undefined | null>) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim()
  }
  return ""
}

function getEmailDomain(email: string) {
  const match = email.trim().toLowerCase().match(/@([^@]+)$/)
  return match?.[1] || ""
}

function inferProviderLabel(host: string, hasResend: boolean) {
  const normalizedHost = host.trim().toLowerCase()
  if (normalizedHost.includes("zoho")) return "Zoho Mail SMTP"
  if (normalizedHost.includes("google") || normalizedHost.includes("gmail")) return "Gmail SMTP"
  if (normalizedHost.includes("outlook") || normalizedHost.includes("office365")) return "Microsoft 365 SMTP"
  if (hasResend) return "Resend API"
  if (normalizedHost) return "Custom SMTP"
  return "Unconfigured"
}

export function buildMailDeliverabilityReport(settings: SiteSettings): MailDeliverabilityReport {
  const canonicalUrl = getSiteUrl()
  const canonicalDomain = (() => {
    try {
      return new URL(canonicalUrl).hostname.replace(/^www\./i, "")
    } catch {
      return "turkishrughouse.com"
    }
  })()

  const smtpHost = envFirst(settings.outgoingMailHost, process.env.SMTP_HOST, process.env.MAIL_HOST)
  const smtpUser = envFirst(settings.outgoingMailUser, process.env.SMTP_USER, process.env.MAIL_USER)
  const fromEmail = envFirst(
    settings.outgoingMailFromEmail,
    settings.supportEmail,
    process.env.SMTP_FROM_EMAIL,
    process.env.MAIL_FROM_EMAIL,
    process.env.NOTIFICATION_FROM_EMAIL,
    process.env.EMAIL_FROM,
    `info@${canonicalDomain}`
  )
  const fromName = envFirst(
    settings.outgoingMailFromName,
    process.env.SMTP_FROM_NAME,
    process.env.MAIL_FROM_NAME,
    settings.siteName,
    "Turkish Rug House"
  )
  const replyTo = envFirst(
    settings.outgoingMailReplyTo,
    settings.supportEmail,
    process.env.SMTP_REPLY_TO,
    process.env.MAIL_REPLY_TO,
    fromEmail
  )
  const providerLabel = inferProviderLabel(smtpHost, Boolean(process.env.RESEND_API_KEY))
  const fromDomain = getEmailDomain(fromEmail)
  const smtpUserDomain = getEmailDomain(smtpUser)
  const warnings: string[] = []
  const recommendations: string[] = []

  if (!smtpHost && !process.env.RESEND_API_KEY) {
    warnings.push("Outgoing email is not configured. Password reset emails cannot be delivered reliably until SMTP or Resend is set.")
  }

  if (providerLabel === "Gmail SMTP") {
    warnings.push("Gmail SMTP is configured for transactional mail. That commonly hurts deliverability and branding for a store domain.")
    recommendations.push("Use a domain-authenticated provider for transactional mail, such as Zoho SMTP for info@turkishrughouse.com or Resend with a verified turkishrughouse.com domain.")
  }

  if (fromDomain && fromDomain !== canonicalDomain) {
    warnings.push(`The current From address (${fromEmail}) is not aligned with ${canonicalDomain}.`)
    recommendations.push(`Set the sender to an address on ${canonicalDomain}, for example info@${canonicalDomain}, and authenticate that domain with SPF, DKIM, and DMARC.`)
  }

  if (smtpUserDomain && fromDomain && smtpUserDomain !== fromDomain && providerLabel !== "Resend API") {
    warnings.push(`SMTP login (${smtpUser}) and From address (${fromEmail}) are on different domains, which can trigger spoofing or spam classification.`)
  }

  if (!replyTo) {
    recommendations.push(`Set Reply-To to a monitored inbox on ${canonicalDomain} so customers can safely reply to password reset emails.`)
  }

  recommendations.push(`Reset links should always use ${canonicalUrl}${PASSWORD_RESET_PATH}.`)

  return {
    canonicalDomain,
    canonicalResetUrl: `${canonicalUrl}${PASSWORD_RESET_PATH}`,
    fromName,
    fromEmail,
    replyTo,
    smtpHost,
    smtpUser,
    providerLabel,
    warnings,
    recommendations,
    dnsRecords: [
      {
        type: "TXT",
        host: "@",
        value: "v=spf1 include:zohomail.com ~all",
        purpose: "Authorize Zoho Mail to send mail for the domain. Merge this into the single existing SPF record instead of creating a second SPF TXT record.",
      },
      {
        type: "TXT",
        host: "default._domainkey",
        value: "Use the DKIM public key generated by your active mail provider.",
        purpose: "DKIM signs outgoing mail so mailbox providers can verify the message was authorized by the domain.",
      },
      {
        type: "TXT",
        host: "_dmarc",
        value: `v=DMARC1; p=none; adkim=s; aspf=s; pct=100; rua=mailto:dmarc@${canonicalDomain}`,
        purpose: "Start DMARC in monitor mode, review reports, then tighten to quarantine or reject after authentication passes cleanly.",
      },
    ],
  }
}
