// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(admin)/dashboard/analytics/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/analytics/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/design-system">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/design">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/media">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/menus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/menus">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/menus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/messages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/messages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/coupons">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/settings/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/settings/[section]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/settings/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/pages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/pages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/pages/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/pages/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/attributes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/attributes">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/attributes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/integration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/integration">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/integration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/account/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/account/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/account/messages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/messages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/account/messages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/account/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/account/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/basket/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/basket">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/basket/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/category/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/info/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/info/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/info/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/info/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/product/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/product/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/saved-searches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saved-searches">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/saved-searches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/rughouse/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rughouse/login">> = Specific
  const handler = {} as typeof import("../../../src/app/rughouse/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/rughouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rughouse">> = Specific
  const handler = {} as typeof import("../../../src/app/rughouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/messages/[id]/thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/messages/[id]/thread">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/messages/[id]/thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/preferences">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/attributes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/attributes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/attributes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/cache/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cache">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/cache/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/categories/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/categories/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/categories/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/categories/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/abandoned-carts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/abandoned-carts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/abandoned-carts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/customer-activity/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/customer-activity/detail">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/customer-activity/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/customer-activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/customer-activity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/customer-activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/device-logins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/device-logins">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/device-logins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/social-logins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/social-logins">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/social-logins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/integrations/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/integrations/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/integrations/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/media/folders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media/folders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/media/folders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/media/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media/optimize">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/media/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/menus/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/menus/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/menus/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/menus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/menus">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/menus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/[id]/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/[id]/reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/[id]/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/[id]/thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/[id]/thread">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/[id]/thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/countries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/countries">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/countries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/messages/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/messages/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/orders/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/orders/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/orders/undo-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/undo-delete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/orders/undo-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/pages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/pages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/pages/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pages/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/pages/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/products/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/products/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/products/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/products/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/products/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/products/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/review-access/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/review-access/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/review-access/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/review-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/review-access">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/review-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/social/callback/[provider]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/social/callback/[provider]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/social/callback/[provider]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/social/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/social/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/social/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/categories/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/categories/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/categories/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/categories/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/faqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/faqs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/faqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menus/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menus/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menus/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menus">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/email/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/email/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/email/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/whatsapp/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/whatsapp/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/whatsapp/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/cart/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cart/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/cart/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/location/cities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/location/cities">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/location/cities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/location/countries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/location/countries">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/location/countries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/location/states/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/location/states">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/location/states/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/menus/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/menus/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/menus/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/menus/location/[location]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/menus/location/[location]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/menus/location/[location]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/menus/primary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/menus/primary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/menus/primary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/pages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/payments/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/payments/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/payments/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/payments/paypal/success/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/payments/paypal/success">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/payments/paypal/success/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/payments/stripe/success/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/payments/stripe/success">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/payments/stripe/success/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/reviews/eligibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reviews/eligibility">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/reviews/eligibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/reviews/showcase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reviews/showcase">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/reviews/showcase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/shipping/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/shipping/quote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/shipping/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/seed-categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/seed-categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/support/faqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support/faqs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/support/faqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/support/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support/tickets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/support/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/public/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/public/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/public/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/public/home/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/public/home">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/public/home/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/public/products/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/public/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/public/products/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/public/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/public/products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/public/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(admin)/dashboard/design-system/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/design-system">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/design-system/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/design/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/design">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/design/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/media/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/media">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/media/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/menus/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/menus">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/menus/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/messages/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/messages/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/orders/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/orders/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/orders/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/pages/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/pages">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/pages/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/users/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/users/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
