import { getSessionUser } from "@/lib/auth-server"
import { redirect } from "next/navigation"
import { getVendorDashboardMetrics } from "@/lib/admin/vendor-dashboard"

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value)
}

function MetricRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
      <span className="text-sm font-medium text-slate-700">{label}</span>
      <span className="text-sm font-semibold text-slate-900">{value}</span>
    </div>
  )
}

function EmptyState({ title }: { title: string }) {
  return (
    <div className="rounded-2xl border border-dashed border-slate-200 bg-white px-6 py-10 text-center text-sm text-slate-500">
      {title}
    </div>
  )
}

export default async function SuperuserDashboardPage() {
  const user = await getSessionUser("admin")
  if (!user) {
    redirect("/rughouse/login")
  }
  if (user.role !== "SUPER_USER") {
    redirect("/dashboard")
  }

  const metrics = await getVendorDashboardMetrics(user.id)
  const hasProducts = metrics.productsAdded.total > 0
  const hasSales = metrics.salesRevenue.total > 0

  return (
    <div className="flex-1 bg-[#f6f7fb] p-6">
      <div className="mx-auto w-full max-w-5xl space-y-6">
        <div className="rounded-[28px] border border-slate-200 bg-white px-7 py-7 shadow-[0_12px_34px_rgba(15,23,42,0.04)]">
          <p className="text-[11px] font-semibold uppercase tracking-[0.26em] text-[#0f766e]">Superuser</p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">Account performance</h1>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">
            This view summarizes products you created and sales generated by those products.
          </p>
        </div>

        <div className="grid gap-5 lg:grid-cols-2">
          <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_12px_34px_rgba(15,23,42,0.04)]">
            <div className="border-b border-slate-200 pb-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.26em] text-[#0f766e]">Products Added</p>
              <h2 className="mt-2 font-serif text-2xl text-slate-900">Catalog contribution</h2>
            </div>

            {!hasProducts ? (
              <div className="mt-5">
                <EmptyState title="No products added yet." />
              </div>
            ) : (
              <div className="mt-5 space-y-3">
                <MetricRow label="Daily" value={`${metrics.productsAdded.daily}`} />
                <MetricRow label="Weekly" value={`${metrics.productsAdded.weekly}`} />
                <MetricRow label="Yearly" value={`${metrics.productsAdded.yearly}`} />
                <MetricRow label="Total" value={`${metrics.productsAdded.total}`} />
              </div>
            )}
          </section>

          <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_12px_34px_rgba(15,23,42,0.04)]">
            <div className="border-b border-slate-200 pb-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.26em] text-[#0f766e]">Sales Performance</p>
              <h2 className="mt-2 font-serif text-2xl text-slate-900">Revenue from your products</h2>
            </div>

            {!hasSales ? (
              <div className="mt-5">
                <EmptyState title="No sales yet." />
              </div>
            ) : (
              <div className="mt-5 space-y-3">
                <MetricRow label="Daily" value={formatCurrency(metrics.salesRevenue.daily)} />
                <MetricRow label="Weekly" value={formatCurrency(metrics.salesRevenue.weekly)} />
                <MetricRow label="Yearly" value={formatCurrency(metrics.salesRevenue.yearly)} />
                <MetricRow label="Total" value={formatCurrency(metrics.salesRevenue.total)} />
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  )
}

